// Item formats: "text" | {h:"Subheading"} | null
// Ticks are saved by position, so a removed item is left as null to keep the
// items after it lined up with their saved ticks.
const PACKING_SECTIONS = [
  { title: "Overnight bag", items: [
    { h: "Friday evening clothes" }, null,
    "T-shirt", "Casual trousers or joggers", "Underwear", "Socks", "Comfortable shoes or trainers",
    { h: "Overnight essentials" },
    "Sleepwear", "Warm hoodie or jumper", null, null, "Toothbrush", "Toothpaste", "Deodorant", "Shower gel",
    null, "Vitamins and supplements", "Wallet", "British Triathlon licence or membership",
    "Breakfast for race morning", "Evening snacks", "AeroPress and coffee"
  ]},
  { title: "Camera and electronics bag", items: [
    "DSLR camera", "Lens 1", "Lens 2", "Spare DSLR batteries", "GoPro", "GoPro charger and cable", "Phone", "Phone charger",
    "Garmin watch", "Garmin watch charger", "Bike computer", "Bike computer charger", "Heart-rate monitor chest strap", "AirPods"
  ]},
  { title: "Race-day kit bag", items: [
    "Race documents and registration details", "Race pack, if issued", "Photo ID", "British Triathlon licence or membership", "Phone",
    "Wallet or bank card", "Car keys", "Timing chip", "Timing chip ankle strap", "Race numbers", "Bike number and stickers",
    "Helmet stickers", "Safety pins", "Permanent marker", "Sunscreen", "Lip balm", null, "BodyGlide or anti-chafe balm",
    "First-aid kit", "Goggles", "Anti-fog solution", "Swim cap", "Nose clip", "Flip-flops or sandals",
    "Warm hoodie or jumper", "Waterproof coat", "Wet bag or dry bag for wetsuit", "Foam roller"
  ]},
  { title: "Race morning clothes", items: [
    "Socks", "T-shirt", "Comfortable shorts", "Hoodie or warm jumper", "Waterproof coat", "Comfortable trainers", "Flip-flops or sliders"
  ]},
  { title: "Worn to the swim start", items: [
    { h: "Kit" },
    "Trisuit", "Wetsuit", "Goggles", "Anti-fog applied to goggles", "Swim cap", "Race-issued swim cap, if required", "Nose clip",
    "Garmin watch", "Heart-rate monitor", "Timing chip",
    { h: "Apply BodyGlide to" }, null,
    "Neck", "Shoulders", "Wrists", "Ankles",
    { h: "While waiting" },
    "Flip-flops or sliders", "Warm hoodie or jumper", "Waterproof coat"
  ]},
  { title: "T1 transition bag: swim to bike", items: [
    "Cycling helmet", "Cycling shoes", "Socks", "Cycling glasses", "Cycling gloves", "Race belt", "Race number attached to race belt",
    "Small towel for drying feet", "Gel or snack for the start of the bike"
  ]},
  { title: "On the bike", items: [
    "Boardman road bike", "Bike computer", "Bike number fitted", "Water bottle 1", "Water bottle 2",
    "Electrolytes or hydration mix in bottles", "Bike gels", "Other bike nutrition", "Nutrition and tool bag", "Saddle bag",
    "Spare inner tube", "Tyre levers", "Mini pump", "Multi-tool"
  ]},
  { title: "T2 transition bag: bike to run", items: [
    "Running shoes", "Fresh running socks", "Running glasses", "Running cap or visor",
    "Race belt and race number, if not already wearing it", "Running gels", "Small towel"
  ]},
  { title: "Spare bike kit (in the car)", items: [
    "Track pump", "Second spare inner tube", "Allen keys", "Spare water bottle", "Spare electrolytes",
    "Spare hydration tablets", "Spare gels", "Spare nutrition"
  ]},
  { title: "Food and drink", items: [
    { h: "Before the race" }, null, "Oranges", "Water", "Pre-race electrolyte drink", "Hydration tablets", "Pre-race gel, if planned",
    null, null, null, null,
    null,
    { h: "After the race" }, "Water", "Electrolytes", "Hydration tablet", "Meal replacement shake", "Recovery food or snacks"
  ]},
  { title: "Warm, dry clothes for after the race", items: [
    "Dry underwear", "Dry socks", "Dry T-shirt", "Warm hoodie or jumper", "Warm trousers or joggers", "Waterproof coat",
    "Dry comfortable trainers", "Beanie or warm hat, if cold", "Large towel", "Wet bag for wetsuit",
    "Plastic bag for wet trisuit and other kit", "Dry robe"
  ]},
  { title: "Bike checks before leaving", items: [
    "Bike mechanically sound", "Tyres checked", "Tyres inflated to chosen pressure", "No obvious tyre cuts or damage", "Wheels secure",
    "Thru-axles or quick releases secure", "Brakes working", "Gears working", "Chain clean and lubricated", "Pedals secure",
    "Bottle cages secure", "Bike computer secure", "Bike computer fully charged", "Bike computer working", "Sensors connected",
    "Heart-rate monitor connected", "Spare tube on bike", "Mini pump on bike", "Multi-tool on bike", "Tyre levers on bike",
    "Gels and nutrition attached or stored", "Both water bottles filled"
  ]}
];

const TASK_SECTIONS = [
  { title: "14 days out", items: [
    "Confirm race entry and registration details",
    "Read race information or athlete guide",
    "Confirm race distances and format",
    "Check start time and wave time",
    "Check how to register and collect your race pack",
    "Check transition rules",
    "Check wetsuit rules",
    "Check parking and venue access",
    "Confirm hotel booking",
    "Plan travel to the hotel and race venue",
    "Check British Triathlon membership or licence",
    "Check bike is mechanically sound",
    "Book bike service if anything needs attention",
    "Check tyres for wear or damage",
    "Check brake pads",
    "Check gears and drivetrain",
    "Check running shoes are in good condition",
    "Make sure wetsuit, goggles and trisuit fit correctly",
    "Decide what you'll eat during the race",
    "Decide what you'll drink during the race",
    "Use only nutrition and equipment you've already tested",
    "Start easing off training"
  ]},
  { title: "7 days out", items: [
    "Re-read race instructions",
    "Check provisional weather forecast",
    "Check water temperature, if available",
    "Confirm travel times",
    "Confirm hotel check-in",
    "Confirm parking arrangements",
    "Plan race-morning breakfast",
    "Plan pre-race nutrition",
    "Plan bike nutrition",
    "Plan run nutrition",
    "Plan post-race nutrition",
    "Buy any missing gels",
    "Buy electrolytes or hydration tablets",
    "Buy oranges and pre-race food",
    "Buy meal replacement or recovery shake",
    "Check all chargers work",
    "Check Garmin",
    "Check bike computer",
    "Check heart-rate monitor battery",
    "Check GoPro",
    "Check camera memory cards",
    "Charge spare DSLR batteries",
    "Make sure race belt is ready",
    "Make sure wet bag is ready",
    "Start organising equipment into packing-list categories"
  ]},
  { title: "3–4 days out", items: [
    "Do your last hard training sessions",
    "Keep remaining training easy",
    "Prioritise sleep",
    "Prioritise hydration",
    "Eat as normal and avoid new foods",
    null,
    "Check updated weather forecast",
    "Decide race clothing based on forecast",
    "Decide whether extra warm or waterproof clothing is needed",
    "Clean bike",
    "Lubricate chain",
    null,
    null,
    null,
    "Check wheels",
    "Check bottle cages",
    "Check pedals",
    "Check bike computer mount",
    "Check saddle bag and tool storage",
    "Check spare inner tube",
    "Check mini pump",
    "Check multi-tool",
    "Check tyre levers",
    "Clean cycling glasses",
    "Clean running glasses",
    "Clean goggles",
    "Test anti-fog solution",
    "Check wetsuit for damage"
  ]},
  { title: "2 days out", items: [
    "Pack overnight bag",
    "Pack camera and electronics bag",
    "Pack race-day kit bag",
    "Pack T1 transition bag",
    "Pack T2 transition bag",
    "Pack the spare bike kit",
    "Prepare warm, dry post-race clothes",
    "Put all nutrition and hydration together",
    "Put race documents together",
    "Download or screenshot race information",
    "Save race venue location",
    "Save parking location",
    "Charge phone",
    "Charge Garmin",
    "Charge bike computer",
    "Charge GoPro",
    "Charge DSLR batteries",
    "Charge AirPods",
    "Empty or format camera memory cards, if needed",
    "Empty or format GoPro memory card, if needed"
  ]},
  { title: "Day before", items: [
    { h: "Final packing and bike prep" },
    "Run through the full packing list",
    "Check bike one final time",
    "Pump tyres to about race pressure",
    "Check front wheel and thru-axle if removing the wheel for transport",
    "Fit bike number if already issued",
    "Fit bike stickers if already issued",
    "Fit helmet stickers if already issued",
    "Mount and check bike computer",
    "Put spare tube, mini pump, tyre levers and multi-tool on bike",
    "Prepare bike nutrition",
    "Prepare running gels",
    "Prepare hydration products for the morning",
    "Prepare race-morning breakfast",
    "Put oranges and pre-race food somewhere obvious",
    "Prepare meal replacement shake for after",
    "Lay out race morning clothes",
    "Put race documents, wallet and car keys together",
    "Load everything into the car except items needed overnight",
    "Load bike in or on the car",
    { h: "Final planning" },
    "Check weather one final time",
    "Check race start and wave time",
    "Confirm hotel-to-venue journey time",
    "Work out what time to leave the hotel",
    "Work out what time to wake up",
    "Set alarm",
    "Set backup alarm",
    { h: "Evening" },
    "Eat a familiar evening meal",
    "Drink as normal",
    "Avoid alcohol",
    "Get an early night"
  ]},
  { title: "Race morning: after waking", items: [
    "Wake up at planned time",
    "Eat race-morning breakfast",
    "Start drinking water and electrolytes",
    "Take normal vitamins and supplements",
    "Put trisuit on",
    "Get dressed in race morning clothes",
    "Put sunscreen on",
    "Put heart-rate monitor on"
  ]},
  { title: "Race morning: final preparation", items: [
    "Fill bike water bottles",
    "Add electrolytes or hydration mix",
    "Put bike gels and nutrition on bike",
    "Take oranges and pre-race food",
    "Take planned pre-race gel, if using one",
    "Check Garmin battery",
    "Check bike computer battery",
    "Check race documents",
    "Check timing chip, if already collected",
    "Check T1 bag",
    "Check T2 bag",
    "Check race-day kit bag",
    "Check camera and electronics bag",
    "Check warm post-race clothes",
    "Load remaining overnight items",
    "Check phone",
    "Check wallet",
    "Check car keys",
    "Check bike",
    "Check race bags",
    "Leave with plenty of spare time"
  ]},
  { title: "Arrive at venue", items: [
    "Park",
    "Take bike and race equipment to event area",
    "Register or collect race pack, if required",
    "Collect timing chip, if required",
    "Attach race numbers and stickers",
    "Put timing chip on (left ankle) before the swim",
    "Check race number is on race belt",
    "Check helmet stickers",
    "Check bike number",
    "Visit toilets early"
  ]},
  { title: "Learn the transition layout", items: [
    "Find transition entrance",
    "Find your rack position",
    "Find the swim start",
    "Find the swim exit",
    "Find bike out",
    "Find bike in",
    "Find run out",
    "Check transition flow",
    "Memorise landmarks near your bike"
  ]},
  { title: "Set up bike and T1", items: [
    "Rack bike correctly",
    "Put bike bottles on bike",
    "Check bike nutrition",
    "Check bike computer",
    "Check heart-rate monitor connection",
    "Put bike in an easy gear for the start",
    "Position helmet",
    "Position cycling shoes",
    "Position cycling glasses",
    "Position race belt",
    "Position T1 towel",
    "Walk through T1 mentally"
  ]},
  { title: "Set up T2", items: [
    "Position running shoes",
    "Position fresh socks",
    "Position running glasses",
    "Position running cap or visor",
    "Position running gels",
    "Position small towel",
    "Walk through T2 mentally"
  ]},
  { title: "Before you leave transition", items: [
    "Make sure everything is laid out how you want it",
    null,
    null,
    null,
    null,
    null,
    null,
    "Leave transition with enough time before the swim start"
  ]},
  { title: "Before the swim", items: [
    "Visit toilet one final time",
    "Don't drink too much just before the start",
    "Apply BodyGlide",
    "Put wetsuit on",
    "Put Garmin into triathlon mode",
    "Check heart-rate monitor",
    "Make sure timing chip is secure",
    "Put swim cap on",
    "Apply anti-fog to goggles",
    "Put goggles on",
    "Put nose clip on",
    "Look at the swim course and turn buoys",
    "Confirm number of swim laps",
    "Hand over warm clothes and waterproof coat, or leave them where instructed",
    "Get to the start with time to spare"
  ]},
  { title: "Immediately after the race", items: [
    { h: "First few minutes" },
    "Stop and save Garmin activity",
    "Drink water or electrolytes",
    "Have meal replacement or recovery shake",
    "Eat recovery food",
    "Put waterproof coat on if cold or wet",
    { h: "Change and recover" },
    "Change into warm, dry clothes",
    "Put wetsuit and wet kit into wet bag",
    { h: "Collect everything" },
    "Collect T1 equipment",
    "Collect T2 equipment",
    "Collect race-day kit bag",
    "Collect bike",
    "Check timing chip return requirements",
    "Check your rack and transition area one final time",
    "Make sure nothing has been left behind",
    "Pack bike safely for the journey home"
  ]}
];
